# Generated by Django 5.2.11 on 2026-02-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ESCOLA', 'Escola'), ('SAUDE', 'Saude')], max_length=30),
        ),
    ]
