# Generated by Django 5.2.11 on 2026-02-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_group',
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NI', 'Nao informado')], default='NI', max_length=2),
        ),
    ]
